### ISSUE TITLE
I Can't Install a mod with custom avatars

### ISSUE THREAD

**Issue by Swipperr** [agc93/beatvortex#5]
i have made a post like this one on the mod makers page and they told me to take this 2 u, so i did video link bla bla bla here [-video-](https://youtu.be/HBjn3epnbfQ)

**Comment by agc93** [comment]
Thanks for reporting this @Swipperr . I'll test out with DynamicOpenVR and see if I can adjust things to work better.

**Comment by agc93** [comment]
Thanks again for reporting this @Swipperr ! This should be fixed in 0.3.7 of the extension which I've just uploaded to Nexus.

Once the update works its way through Nexus (usually a day or so), Vortex should auto-update and you can try installing those mods again. Let me know if you hit any more problems! 👍
